/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./pages/__root"
import { Route as LayoutRouteImport } from "./pages/_layout"
import { Route as AuthRouteImport } from "./pages/_auth"
import { Route as LayoutIndexRouteImport } from "./pages/_layout/index"
import { Route as LayoutEmployeesRouteImport } from "./pages/_layout/employees"
import { Route as LayoutChecklistRouteImport } from "./pages/_layout/checklist"
import { Route as AuthLoginRouteImport } from "./pages/_auth/login"

const LayoutRoute = LayoutRouteImport.update({
  id: "/_layout",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEmployeesRoute = LayoutEmployeesRouteImport.update({
  id: "/employees",
  path: "/employees",
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChecklistRoute = LayoutChecklistRouteImport.update({
  id: "/checklist",
  path: "/checklist",
  getParentRoute: () => LayoutRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  "/login": typeof AuthLoginRoute
  "/checklist": typeof LayoutChecklistRoute
  "/employees": typeof LayoutEmployeesRoute
  "/": typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  "/login": typeof AuthLoginRoute
  "/checklist": typeof LayoutChecklistRoute
  "/employees": typeof LayoutEmployeesRoute
  "/": typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_auth": typeof AuthRouteWithChildren
  "/_layout": typeof LayoutRouteWithChildren
  "/_auth/login": typeof AuthLoginRoute
  "/_layout/checklist": typeof LayoutChecklistRoute
  "/_layout/employees": typeof LayoutEmployeesRoute
  "/_layout/": typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/login" | "/checklist" | "/employees" | "/"
  fileRoutesByTo: FileRoutesByTo
  to: "/login" | "/checklist" | "/employees" | "/"
  id:
    | "__root__"
    | "/_auth"
    | "/_layout"
    | "/_auth/login"
    | "/_layout/checklist"
    | "/_layout/employees"
    | "/_layout/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_layout": {
      id: "/_layout"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth": {
      id: "/_auth"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_layout/": {
      id: "/_layout/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    "/_layout/employees": {
      id: "/_layout/employees"
      path: "/employees"
      fullPath: "/employees"
      preLoaderRoute: typeof LayoutEmployeesRouteImport
      parentRoute: typeof LayoutRoute
    }
    "/_layout/checklist": {
      id: "/_layout/checklist"
      path: "/checklist"
      fullPath: "/checklist"
      preLoaderRoute: typeof LayoutChecklistRouteImport
      parentRoute: typeof LayoutRoute
    }
    "/_auth/login": {
      id: "/_auth/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LayoutRouteChildren {
  LayoutChecklistRoute: typeof LayoutChecklistRoute
  LayoutEmployeesRoute: typeof LayoutEmployeesRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutChecklistRoute: LayoutChecklistRoute,
  LayoutEmployeesRoute: LayoutEmployeesRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
